export const CartActionTypes = {
  TOGGLE_CART_DROPDOWN: "TOGGLE_CART_DROPDOWN",
  ADD_TO_CART: "ADD_TO_CART",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  DECREASE_FROM_CART: "DECREASE_FROM_CART"
};
